#############################################################################
# Makefile for building: 3DGraph
# Generated by qmake (2.01a) (Qt 4.6.0) on: Tue Mar 9 00:46:21 2010
# Project:  3DGraph.pro
# Template: app
# Command: /home/lucio/qtsdk-2009.05/qt/bin/qmake -spec ../../../qtsdk-2009.05/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile 3DGraph.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../qtsdk-2009.05/qt/mkspecs/linux-g++-64 -I. -I../../../qtsdk-2009.05/qt/include/QtCore -I../../../qtsdk-2009.05/qt/include/QtGui -I../../../qtsdk-2009.05/qt/include/QtOpenGL -I../../../qtsdk-2009.05/qt/include -I/usr/X11R6/include -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-rpath,/home/lucio/qtsdk-2009.05/qt/lib
LIBS          = $(SUBLIBS)  -L/home/lucio/qtsdk-2009.05/qt/lib -L/usr/X11R6/lib64 -lQtOpenGL -L/home/lucio/qtsdk-2009.05/qt/lib -L/usr/X11R6/lib64 -lQtGui -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/lucio/qtsdk-2009.05/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = window.cpp \
		sceneElement.cpp \
		main.cpp \
		glwidget.cpp \
		sceneManager/pipeEntity.cpp \
		sceneManager/patch.cpp \
		sceneManager/nodeEntity.cpp \
		sceneManager/netEntity.cpp moc_window.cpp \
		moc_glwidget.cpp
OBJECTS       = window.o \
		sceneElement.o \
		main.o \
		glwidget.o \
		pipeEntity.o \
		patch.o \
		nodeEntity.o \
		netEntity.o \
		moc_window.o \
		moc_glwidget.o
DIST          = ../../../qtsdk-2009.05/qt/mkspecs/common/g++.conf \
		../../../qtsdk-2009.05/qt/mkspecs/common/unix.conf \
		../../../qtsdk-2009.05/qt/mkspecs/common/linux.conf \
		../../../qtsdk-2009.05/qt/mkspecs/qconfig.pri \
		../../../qtsdk-2009.05/qt/mkspecs/features/qt_functions.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/qt_config.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/exclusive_builds.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/default_pre.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/debug.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/default_post.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/warn_on.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/qt.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/unix/opengl.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/unix/thread.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/moc.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/resources.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/uic.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/yacc.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/lex.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/include_source_dir.prf \
		3DGraph.pro
QMAKE_TARGET  = 3DGraph
DESTDIR       = 
TARGET        = 3DGraph

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: 3DGraph.pro  ../../../qtsdk-2009.05/qt/mkspecs/linux-g++-64/qmake.conf ../../../qtsdk-2009.05/qt/mkspecs/common/g++.conf \
		../../../qtsdk-2009.05/qt/mkspecs/common/unix.conf \
		../../../qtsdk-2009.05/qt/mkspecs/common/linux.conf \
		../../../qtsdk-2009.05/qt/mkspecs/qconfig.pri \
		../../../qtsdk-2009.05/qt/mkspecs/features/qt_functions.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/qt_config.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/exclusive_builds.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/default_pre.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/debug.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/default_post.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/warn_on.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/qt.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/unix/opengl.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/unix/thread.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/moc.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/resources.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/uic.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/yacc.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/lex.prf \
		../../../qtsdk-2009.05/qt/mkspecs/features/include_source_dir.prf \
		/home/lucio/qtsdk-2009.05/qt/lib/libQtOpenGL.prl \
		/home/lucio/qtsdk-2009.05/qt/lib/libQtGui.prl \
		/home/lucio/qtsdk-2009.05/qt/lib/libQtCore.prl
	$(QMAKE) -spec ../../../qtsdk-2009.05/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile 3DGraph.pro
../../../qtsdk-2009.05/qt/mkspecs/common/g++.conf:
../../../qtsdk-2009.05/qt/mkspecs/common/unix.conf:
../../../qtsdk-2009.05/qt/mkspecs/common/linux.conf:
../../../qtsdk-2009.05/qt/mkspecs/qconfig.pri:
../../../qtsdk-2009.05/qt/mkspecs/features/qt_functions.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/qt_config.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/exclusive_builds.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/default_pre.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/debug.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/default_post.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/warn_on.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/qt.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/unix/opengl.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/unix/thread.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/moc.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/resources.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/uic.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/yacc.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/lex.prf:
../../../qtsdk-2009.05/qt/mkspecs/features/include_source_dir.prf:
/home/lucio/qtsdk-2009.05/qt/lib/libQtOpenGL.prl:
/home/lucio/qtsdk-2009.05/qt/lib/libQtGui.prl:
/home/lucio/qtsdk-2009.05/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../../qtsdk-2009.05/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile 3DGraph.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/3DGraph1.0.0 || $(MKDIR) .tmp/3DGraph1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/3DGraph1.0.0/ && $(COPY_FILE) --parents window.h sceneElement.h glwidget.h sceneManager/pipeEntity.h sceneManager/patch.h sceneManager/nodeEntity.h sceneManager/netEntity.h .tmp/3DGraph1.0.0/ && $(COPY_FILE) --parents window.cpp sceneElement.cpp main.cpp glwidget.cpp sceneManager/pipeEntity.cpp sceneManager/patch.cpp sceneManager/nodeEntity.cpp sceneManager/netEntity.cpp .tmp/3DGraph1.0.0/ && (cd `dirname .tmp/3DGraph1.0.0` && $(TAR) 3DGraph1.0.0.tar 3DGraph1.0.0 && $(COMPRESS) 3DGraph1.0.0.tar) && $(MOVE) `dirname .tmp/3DGraph1.0.0`/3DGraph1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/3DGraph1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_window.cpp moc_glwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_window.cpp moc_glwidget.cpp
moc_window.cpp: window.h
	/home/lucio/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) window.h -o moc_window.cpp

moc_glwidget.cpp: sceneElement.h \
		sceneManager/patch.h \
		sceneManager/nodeEntity.h \
		sceneManager/netEntity.h \
		sceneManager/pipeEntity.h \
		glwidget.h
	/home/lucio/qtsdk-2009.05/qt/bin/moc $(DEFINES) $(INCPATH) glwidget.h -o moc_glwidget.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

window.o: window.cpp glwidget.h \
		sceneElement.h \
		sceneManager/patch.h \
		sceneManager/nodeEntity.h \
		sceneManager/netEntity.h \
		sceneManager/pipeEntity.h \
		window.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cpp

sceneElement.o: sceneElement.cpp sceneElement.h \
		sceneManager/patch.h \
		sceneManager/nodeEntity.h \
		sceneManager/netEntity.h \
		sceneManager/pipeEntity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sceneElement.o sceneElement.cpp

main.o: main.cpp window.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

glwidget.o: glwidget.cpp glwidget.h \
		sceneElement.h \
		sceneManager/patch.h \
		sceneManager/nodeEntity.h \
		sceneManager/netEntity.h \
		sceneManager/pipeEntity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glwidget.o glwidget.cpp

pipeEntity.o: sceneManager/pipeEntity.cpp sceneManager/pipeEntity.h \
		sceneManager/netEntity.h \
		sceneManager/patch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pipeEntity.o sceneManager/pipeEntity.cpp

patch.o: sceneManager/patch.cpp sceneManager/patch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o patch.o sceneManager/patch.cpp

nodeEntity.o: sceneManager/nodeEntity.cpp sceneManager/nodeEntity.h \
		sceneManager/netEntity.h \
		sceneManager/patch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nodeEntity.o sceneManager/nodeEntity.cpp

netEntity.o: sceneManager/netEntity.cpp sceneManager/netEntity.h \
		sceneManager/patch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o netEntity.o sceneManager/netEntity.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

moc_glwidget.o: moc_glwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glwidget.o moc_glwidget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

